workflows:
  prisonpay-debug:
    name: PrisonPay Debug Build
    max_build_duration: 20
    environment:
      java: 17
    scripts:
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - mrarnoldsd@gmail.com
        notify:
          success: true
          failure: true
